spring:
  application:
    name: service-hi
  zipkin: 
    base-url: http://localhost:9411
    
server: 
  port: 5227
  
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:5220/eureka/