spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: asuka
    password: asuka
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh