# Tomcat
server: 
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8080
  servlet:
    context-path: /renren-admin
spring:
  profiles:
    active: dev
  http:
    multipart:
      servlet:
        max-file-size: 100MB
        max-request-size: 100MB
        enabled: true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 
    timeout: 6000
    jedis:
      pool:
        max-active: 1000
        max-wait: -1
        max-idle: 10
        min-idle: 5
  freemarker:
    suffix: .html
    request-context-attribute: request
renren: 
  redis:
    open: false # 是否开启redis缓存  true开启   false关闭
  shiro:
    redis: false # true表示shiro session存到redis里，需要开启redis，才会生效【分布式场景】
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  typeAliasesPackage: io.renren.modules.*.entity
  global-config:
    id-type: 0
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
    logic-delete-value: -1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
logging:
  level:
    io.renren: debug