server: 
  port: 5220
spring: 
  datasource: 
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    passworld: 
  jpa: 
    database: h2
    hibernate: 
      ddl-auto: update
  h2:
    console:
      path: /h2
      enabled: true